In [75]:
#IMPORTING THE LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [76]:
#READING THE DATA SET
data = pd.read_csv('train.csv')

In [77]:
#SETTING FEATURES AND OUTPUT
X  = data.iloc[:,2:].values
y = data.iloc[:,1:2].values
# X.shape
# X

In [78]:
#DROPPING UNNECESSARY COLUMNS
columns_to_delete = [1,4,5,6,8]
X = np.delete(X, columns_to_delete, axis=1)

In [80]:
X

array([[3, 'male', 22.0, 7.25, 'S'],
       [1, 'female', 38.0, 71.2833, 'C'],
       [3, 'female', 26.0, 7.925, 'S'],
       ...,
       [3, 'female', nan, 23.45, 'S'],
       [1, 'male', 26.0, 30.0, 'C'],
       [3, 'male', 32.0, 7.75, 'Q']], dtype=object)

In [81]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_encoded[:,2:3])
X[:,2:3] = imputer.transform(X[:,2:3])

In [83]:
 # X[:,2:3]

In [84]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:,-1:])
X[:,-1:] = imputer.transform(X[:,-1:])

In [87]:
X

array([[3, 'male', 22.0, 7.25, 'S'],
       [1, 'female', 38.0, 71.2833, 'C'],
       [3, 'female', 26.0, 7.925, 'S'],
       ...,
       [3, 'female', 0.35241301907968575, 23.45, 'S'],
       [1, 'male', 26.0, 30.0, 'C'],
       [3, 'male', 32.0, 7.75, 'Q']], dtype=object)

In [88]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
encoder = OneHotEncoder()

# Create ColumnTransformer
ct = ColumnTransformer([('one_hot_encoder', encoder, [1,4])], remainder='passthrough')

# Fit and transform the data
X_encoded = ct.fit_transform(X)
# X_encoded
X = X_encoded

In [89]:
X

array([[0.0, 1.0, 0.0, ..., 3, 22.0, 7.25],
       [1.0, 0.0, 1.0, ..., 1, 38.0, 71.2833],
       [1.0, 0.0, 0.0, ..., 3, 26.0, 7.925],
       ...,
       [1.0, 0.0, 0.0, ..., 3, 0.35241301907968575, 23.45],
       [0.0, 1.0, 1.0, ..., 1, 26.0, 30.0],
       [0.0, 1.0, 0.0, ..., 3, 32.0, 7.75]], dtype=object)

In [92]:
X[1:5,:]

array([[1.0, 0.0, 1.0, 0.0, 0.0, 1, 38.0, 71.2833],
       [1.0, 0.0, 0.0, 0.0, 1.0, 3, 26.0, 7.925],
       [1.0, 0.0, 0.0, 0.0, 1.0, 1, 35.0, 53.1],
       [0.0, 1.0, 0.0, 0.0, 1.0, 3, 35.0, 8.05]], dtype=object)

In [94]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:,5:] = sc.fit_transform(X[:,5:])

In [96]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [104]:
regressor.fit(X, y)

LinearRegression()

In [105]:
y_pred = regressor.predict(X)

In [106]:
y_pred

array([[ 0.07547692],
       [ 0.95820502],
       [ 0.57160762],
       [ 0.89060921],
       [ 0.04745568],
       [ 0.15987435],
       [ 0.34479555],
       [ 0.11940041],
       [ 0.56962225],
       [ 0.83979411],
       [ 0.61957572],
       [ 0.8395214 ],
       [ 0.07983778],
       [ 0.04007596],
       [ 0.59750947],
       [ 0.67743313],
       [ 0.15743474],
       [ 0.29051508],
       [ 0.56135822],
       [ 0.70002722],
       [ 0.21642041],
       [ 0.21787645],
       [ 0.63295928],
       [ 0.40003998],
       [ 0.611177  ],
       [ 0.54697029],
       [ 0.19529778],
       [ 0.43176758],
       [ 0.66457248],
       [ 0.12224478],
       [ 0.44680304],
       [ 1.04354611],
       [ 0.6645655 ],
       [ 0.1486595 ],
       [ 0.47565221],
       [ 0.37070866],
       [ 0.19529801],
       [ 0.07767897],
       [ 0.58942271],
       [ 0.67078186],
       [ 0.54146812],
       [ 0.73815   ],
       [ 0.19533405],
       [ 0.86416311],
       [ 0.62431595],
       [ 0

In [108]:
from sklearn.metrics import r2_score

# Assuming y and y_pred are NumPy arrays containing the actual and predicted values respectively
r_squared = r2_score(y, y_pred)
print("R-squared score:", r_squared)


R-squared score: 0.3777247909500724
