# Titanic Survival Prediction model

#Importing the libraries

In [133]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Reading the CSV Files

In [134]:
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')

Splitting into X and y

In [135]:
X_train = train.iloc[:,2:].values
#The prediction result i.e. survival status is in index 1
y_train = train.iloc[:,1].values
X_test  = test.iloc[:,1:].values


Imputing the AGE column with mean



In [136]:
X_test[:,3:4]

array([[34.5],
       [47.0],
       [62.0],
       [27.0],
       [22.0],
       [14.0],
       [30.0],
       [26.0],
       [18.0],
       [21.0],
       [nan],
       [46.0],
       [23.0],
       [63.0],
       [47.0],
       [24.0],
       [35.0],
       [21.0],
       [27.0],
       [45.0],
       [55.0],
       [9.0],
       [nan],
       [21.0],
       [48.0],
       [50.0],
       [22.0],
       [22.5],
       [41.0],
       [nan],
       [50.0],
       [24.0],
       [33.0],
       [nan],
       [30.0],
       [18.5],
       [nan],
       [21.0],
       [25.0],
       [nan],
       [39.0],
       [nan],
       [41.0],
       [30.0],
       [45.0],
       [25.0],
       [45.0],
       [nan],
       [60.0],
       [36.0],
       [24.0],
       [27.0],
       [20.0],
       [28.0],
       [nan],
       [10.0],
       [35.0],
       [25.0],
       [nan],
       [36.0],
       [17.0],
       [32.0],
       [18.0],
       [22.0],
       [13.0],
       [nan],
       [18.0],
       

In [137]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

#imputing the training dataset
imputer.fit(X_train[:,3:4])
X_train[:,3:4] = imputer.transform(X_train[:,3:4])

#imputing the testing dataset
imputer.fit(X_test[:,3:4])
X_test[:,3:4] = imputer.transform(X_test[:,3:4])

In [138]:
# X_train[:1:5,:]
X_test[:,3:4]

array([[34.5],
       [47.0],
       [62.0],
       [27.0],
       [22.0],
       [14.0],
       [30.0],
       [26.0],
       [18.0],
       [21.0],
       [30.272590361445783],
       [46.0],
       [23.0],
       [63.0],
       [47.0],
       [24.0],
       [35.0],
       [21.0],
       [27.0],
       [45.0],
       [55.0],
       [9.0],
       [30.272590361445783],
       [21.0],
       [48.0],
       [50.0],
       [22.0],
       [22.5],
       [41.0],
       [30.272590361445783],
       [50.0],
       [24.0],
       [33.0],
       [30.272590361445783],
       [30.0],
       [18.5],
       [30.272590361445783],
       [21.0],
       [25.0],
       [30.272590361445783],
       [39.0],
       [30.272590361445783],
       [41.0],
       [30.0],
       [45.0],
       [25.0],
       [45.0],
       [30.272590361445783],
       [60.0],
       [36.0],
       [24.0],
       [27.0],
       [20.0],
       [28.0],
       [30.272590361445783],
       [10.0],
       [35.0],
       [25.0],
     

In [139]:
X_test

array([[3, 'Kelly, Mr. James', 'male', ..., 7.8292, nan, 'Q'],
       [3, 'Wilkes, Mrs. James (Ellen Needs)', 'female', ..., 7.0, nan,
        'S'],
       [2, 'Myles, Mr. Thomas Francis', 'male', ..., 9.6875, nan, 'Q'],
       ...,
       [3, 'Saether, Mr. Simon Sivertsen', 'male', ..., 7.25, nan, 'S'],
       [3, 'Ware, Mr. Frederick', 'male', ..., 8.05, nan, 'S'],
       [3, 'Peter, Master. Michael J', 'male', ..., 22.3583, nan, 'C']],
      dtype=object)

Using the OneHotEncoder for the Embarked

In [140]:
X_test[:5,9:10]

array([['Q'],
       ['S'],
       ['Q'],
       ['S'],
       ['S']], dtype=object)

In [141]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')

#Encoding the training dataset
X_train = ct.fit_transform(X_train)

#Encoding the testing dataset
X_test = ct.fit_transform(X_test)

In [143]:
X_train[1:5,:]

array([[1.0, 0.0, 0.0, 0.0, 1,
        'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female',
        38.0, 1, 0, 'PC 17599', 71.2833, 'C85'],
       [0.0, 0.0, 1.0, 0.0, 3, 'Heikkinen, Miss. Laina', 'female', 26.0,
        0, 0, 'STON/O2. 3101282', 7.925, nan],
       [0.0, 0.0, 1.0, 0.0, 1,
        'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0,
        1, 0, '113803', 53.1, 'C123'],
       [0.0, 0.0, 1.0, 0.0, 3, 'Allen, Mr. William Henry', 'male', 35.0,
        0, 0, '373450', 8.05, nan]], dtype=object)

Deleting the entire Cabin, Name, Tickets columns since it doesn't have much significance 

In [97]:
X_train = np.delete(X_train, [12,5,10], axis = 1)

In [98]:
X_train[1:5,:]

array([[1.0, 0.0, 0.0, 0.0, 1, 'female', 38.0, 1, 0, 71.2833],
       [0.0, 0.0, 1.0, 0.0, 3, 'female', 26.0, 0, 0, 7.925],
       [0.0, 0.0, 1.0, 0.0, 1, 'female', 35.0, 1, 0, 53.1],
       [0.0, 0.0, 1.0, 0.0, 3, 'male', 35.0, 0, 0, 8.05]], dtype=object)

APPLYING THE ONEhOTeCODING TO GENDER AS WELL WE GET

In [99]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X_train = ct.fit_transform(X_train)

In [100]:
X_train[1:5,:]

array([[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1, 38.0, 1, 0, 71.2833],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 3, 26.0, 0, 0, 7.925],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1, 35.0, 1, 0, 53.1],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3, 35.0, 0, 0, 8.05]], dtype=object)

In [102]:
pd.DataFrame(X_train[1:5,:])

0    1    2    3    4    5  6     7  8  9        10
0  1.0  0.0  1.0  0.0  0.0  0.0  1  38.0  1  0  71.2833
1  1.0  0.0  0.0  0.0  1.0  0.0  3  26.0  0  0    7.925
2  1.0  0.0  0.0  0.0  1.0  0.0  1  35.0  1  0     53.1
3  0.0  1.0  0.0  0.0  1.0  0.0  3  35.0  0  0     8.05

In [103]:
pd.DataFrame(y_train)

0
0    0
1    1
2    1
3    1
4    0
..  ..
886  0
887  1
888  0
889  1
890  0

[891 rows x 1 columns]

Using the basic Regression model

In [106]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

predicting the outcomes

In [107]:
y_pred = regressor.predict(X_test)

ValueError: could not convert string to float: 'Kelly, Mr. James'